#! /bin/bash

SRC_DIR=src
OUT_DIR=exe
JAVA=java

mkdir -p exe
make
set -x

# 4 arguments
# num_features num_hidden radius type
# num_features: 64 (since 8x8)
# num_hidden: 5
# radius: some integer between 1 to 7 (or higher, but probably won't finish)
# type: one of "zero", "eight", or "smile"
num_features=64
num_hidden=5
radius=6
type=zero

# comment these 2 lines out if BNN is already trained
cd bnn/BinaryNet
./run ${num_hidden} ${num_features}
cd ../../

${JAVA} -Xmx100g -cp ${OUT_DIR} bnncompiler.core.LearnOddFromBNNCnf ${num_features} ${num_hidden} ${radius} ${type}
