language: cpp
dist: trusty
compiler: g++
sudo: required

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "cJDvRJ3pvCc9yALvzZVUeUZVuR+y/LWkkSlmPCY7oONCsHb+U0aVXzd+F6SHN+K105iKd0gVbB5gg5MWJ8RE7UyWoxdZGc1t39yxXZQy9YfzhEsn1KsSZWZi3KJNOjtWYfYDaBpPl4xbgoKXhWj+bMC9qXAwLhksornOtVne9EQsFTf1lB4Pr+K5Os3ZSVt5ie7ry7P7GDPvdQCaINh2qDxdEEdIgTYXAkvI3xBbVLZ6TGR8Fv+efMouH1UmkW3nelKj734i1hSD/UvbT/hCt+3wNL3VsDb5BigqHrXwmBpYnW4qIq24dqqTlBY9ydJRtx2HdDuZw/dnFdhc5MNgjEfiZr1tdIpF61pXr2+jHBEZ/A+Kc8kAMf7LzAZQw/2eQO2yjIYkyiETiJB8FT4Nr47z1qf8ctDiGpQluFlM79VUjec7SLH/8THE+rBjaZXuXWZG5Q/VMjldVZrweTujZnj8YjR6mSMwb1hrgp4ulP0ZRLNngquQYBqISJ/fRt4w+k7P41VwWnJlJHGZutwbolnL/HtLUQdlL9i2B+9qE/9BQOUOdTpXlvAckuiPtrBf0kTLQfnmTzlS2NfZeJUWfpL+oig7IO2RgCASj6OUD3NicYrBkmt+3CHxWorfrWTcBvoirQkQBFy3er3Sjda/TxfcHsHfK2DYGKnUFYB+kx4="

# Riss requires cmake version 2.8.8 or higher, Travis might come with 2.8.7
#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#      - george-edison55-precise-backports
#    packages:
#      - cmake-data
#      - cmake
#      - g++-5

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get remove gcc g++
  - sudo apt-get install g++-5 gcc-5 -y
  - sudo apt-get install picosat
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  - sudo update-alternatives --install /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-5 60
  - sudo update-alternatives --install /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-5 60
  - sudo update-alternatives --install /usr/bin/x86_64-linux-gnu-gcc x86_64-linux-gnu-gcc /usr/bin/x86_64-linux-gnu-gcc-5 60 --slave /usr/bin/x86_64-linux-gnu-g++ x86_64-linux-gnu-g++ /usr/bin/x86_64-linux-gnu-g++-5
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "nmanthey/riss-solver"
      description: "Build submitted via Travis CI"
    notification_email: norbert.manthey@googlemail.com
    build_command_prepend: "mkdir -p coverity-dir; cd coverity-dir; cmake -DDRATPROOF=ON -DCMAKE_BUILD_TYPE=Release ..; make clean"
    build_command: "make all -j 4"
    branch_pattern: master

# install a recent version of astyle
before_script:
  - pwd
  - ls -l ..
  - pushd .
  - cd $(mktemp -d) && wget -O astyle.tar.gz "https://downloads.sourceforge.net/project/astyle/astyle/astyle%203.0.1/astyle_3.0.1_linux.tar.gz" && tar xzf astyle.tar.gz && cd astyle/build/gcc/ && make release && export PATH=$(pwd)/bin:$PATH
  - popd

# run the typical ci checks, run code style check first
script:
  - which g++ && which gcc && g++ -dumpversion
  - regression/test-codestyle.sh
  - scripts/ci.sh
